##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.2.0-B44] date: [Sat Mar 16 11:16:36 CET 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

a=$(echo "aaa")

######################################
# target
######################################
TARGET = test

######################################
# ctags variables
######################################

CTAGS_PROG = ctags
CTAGS_OPT = --recurse=yes --exclude=build --tag-relative --extra=+f
CTAGS_TARGET = tags

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/freertos.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Core/Src/system_stm32f4xx.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c

#Middlewares/Third_Party/FreeRTOS-TCP/Source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f429xx.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F429xx


# AS includes
AS_INCLUDES =  \
-ICore/Inc

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# FreeRTOS-TCP
#######################################

C_INCLUDES += \
-IMiddlewares/Third_Party/FreeRTOS-Plus-TCP/Source/portable/Compiler/GCC \
-IMiddlewares/Third_Party/FreeRTOS-Plus-TCP/Source/include
#-IMiddlewares/Third_Party/FreeRTOS-TCP/Source/portable/NetworkInterface/include

C_SOURCES += \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_ARP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_BitConfig.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_DHCP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_DHCPv6.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_DNS.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_DNS_Cache.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_DNS_Callback.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_DNS_Networking.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_DNS_Parser.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_ICMP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IP_Timers.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IP_Utils.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IPv4.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IPv4_Sockets.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IPv4_Utils.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IPv6.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IPv6_Sockets.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_IPv6_Utils.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_ND.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_RA.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_Routing.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_Sockets.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_Stream_Buffer.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_IP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_IP_IPv4.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_IP_IPv6.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_Reception.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_State_Handling.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_State_Handling_IPv4.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_State_Handling_IPv6.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_Transmission.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_Transmission_IPv4.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_Transmission_IPv6.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_Utils.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_Utils_IPv4.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_Utils_IPv6.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_TCP_WIN.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_Tiny_TCP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_UDP_IP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_UDP_IPv4.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/FreeRTOS_UDP_IPv6.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/Source/portable/BufferManagement/BufferAllocation_2.c
#Middlewares/Third_Party/FreeRTOS-TCP/Source/portable/NetworkInterface/Common/phyHandling.c
#Middlewares/Third_Party/FreeRTOS-TCP/Source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F429ZITx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin ctags


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
	-rm -f $(CTAGS_TARGET)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

#######################################
# ctags
#######################################
ctags: $(BUILD_DIR)/$(TARGET).elf
	$(CTAGS_PROG) $(CTAGS_OPT) -f ./$(CTAGS_TARGET) .

#######################################
# .phony
#######################################
.phony: clean ctags

# *** EOF ***
