#!/bin/sh

TARGET="./build/test.bin"

USAGE=\
"Usage: $0 <flash|reset|gdb>"
USAGE_GDB=\
"Usage: $0 gdb <server|attach>"
USAGE_DETAIL=\
"$0 <flash|reset>
$0 gdb <server|attach>

$0 flash [file]  flash the firmware to board
$0 reset         reset board to initial state
$0 gdb server    start gdb server
$0 gdb attach    attach to local gdb server"
 
if [ $# -lt 1 ]; then
	echo "$USAGE_DETAIL"
	exit 1
fi

case $1 in
	"flash")
		[ $2 ] && TARGET=$2
		echo Writing $TARGET to board
		st-flash --reset write $TARGET 0x8000000 2> /dev/null
		if [ $? -eq 0 ]; then
			echo Flashed successfully
		else
			echo Error
		fi
		;;
	"reset")
		st-flash reset
		;;
	"gdb")
		if [ $# -lt 2 ]; then
			echo "$USAGE_GDB"
			exit 1
		fi
		case $2 in
			"server")
				openocd -f board/st_nucleo_f4.cfg
				;;
			"attach")
				gdb ./build/test.elf \
					-ex "set confirm off" \
					-ex "b main" \
					-ex "target extended-remote :3333" \
					-ex "r" \
					-ex "set confirm on"
				;;
			*)
				echo "$USAGE_GDB"
				exit 1
				;;
		esac
		;;
	*)
		echo "$USAGE"
		exit 1
		;;
esac

exit 0
